/**
 * Mock Data - Données de test pour DataTable
 *
 * OBJECTIF :
 * Générer 50 utilisateurs fictifs pour tester le DataTable
 * Données réalistes en français
 */

export interface User {
  id: string
  name: string
  email: string
  role: 'admin' | 'manager' | 'employee' | 'viewer'
  status: 'actif' | 'inactif'
  createdAt: string
}

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sophie Martin',
    email: 'sophie.martin@smartplanning.fr',
    role: 'admin',
    status: 'actif',
    createdAt: '2024-01-15T10:30:00Z',
  },
  {
    id: '2',
    name: 'Thomas Dubois',
    email: 'thomas.dubois@smartplanning.fr',
    role: 'manager',
    status: 'actif',
    createdAt: '2024-01-20T14:15:00Z',
  },
  {
    id: '3',
    name: 'Marie Lefebvre',
    email: 'marie.lefebvre@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-02-01T09:00:00Z',
  },
  {
    id: '4',
    name: 'Pierre Moreau',
    email: 'pierre.moreau@smartplanning.fr',
    role: 'employee',
    status: 'inactif',
    createdAt: '2024-02-05T11:30:00Z',
  },
  {
    id: '5',
    name: 'Julie Bernard',
    email: 'julie.bernard@smartplanning.fr',
    role: 'manager',
    status: 'actif',
    createdAt: '2024-02-10T08:45:00Z',
  },
  {
    id: '6',
    name: 'Alexandre Petit',
    email: 'alexandre.petit@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-02-15T16:20:00Z',
  },
  {
    id: '7',
    name: 'Camille Durand',
    email: 'camille.durand@smartplanning.fr',
    role: 'viewer',
    status: 'actif',
    createdAt: '2024-02-20T10:00:00Z',
  },
  {
    id: '8',
    name: 'Lucas Robert',
    email: 'lucas.robert@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-02-25T13:30:00Z',
  },
  {
    id: '9',
    name: 'Emma Richard',
    email: 'emma.richard@smartplanning.fr',
    role: 'manager',
    status: 'actif',
    createdAt: '2024-03-01T09:15:00Z',
  },
  {
    id: '10',
    name: 'Hugo Simon',
    email: 'hugo.simon@smartplanning.fr',
    role: 'employee',
    status: 'inactif',
    createdAt: '2024-03-05T14:45:00Z',
  },
  {
    id: '11',
    name: 'Léa Laurent',
    email: 'lea.laurent@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-03-10T11:00:00Z',
  },
  {
    id: '12',
    name: 'Nathan Michel',
    email: 'nathan.michel@smartplanning.fr',
    role: 'viewer',
    status: 'actif',
    createdAt: '2024-03-15T15:30:00Z',
  },
  {
    id: '13',
    name: 'Chloé Fontaine',
    email: 'chloe.fontaine@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-03-20T10:20:00Z',
  },
  {
    id: '14',
    name: 'Louis Garcia',
    email: 'louis.garcia@smartplanning.fr',
    role: 'manager',
    status: 'actif',
    createdAt: '2024-03-25T12:00:00Z',
  },
  {
    id: '15',
    name: 'Sarah Martinez',
    email: 'sarah.martinez@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-04-01T09:30:00Z',
  },
  {
    id: '16',
    name: 'Arthur Roux',
    email: 'arthur.roux@smartplanning.fr',
    role: 'employee',
    status: 'inactif',
    createdAt: '2024-04-05T14:00:00Z',
  },
  {
    id: '17',
    name: 'Manon Vincent',
    email: 'manon.vincent@smartplanning.fr',
    role: 'viewer',
    status: 'actif',
    createdAt: '2024-04-10T11:45:00Z',
  },
  {
    id: '18',
    name: 'Gabriel Fournier',
    email: 'gabriel.fournier@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-04-15T16:15:00Z',
  },
  {
    id: '19',
    name: 'Zoé Morel',
    email: 'zoe.morel@smartplanning.fr',
    role: 'manager',
    status: 'actif',
    createdAt: '2024-04-20T10:30:00Z',
  },
  {
    id: '20',
    name: 'Maxime Girard',
    email: 'maxime.girard@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-04-25T13:00:00Z',
  },
  {
    id: '21',
    name: 'Inès André',
    email: 'ines.andre@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-05-01T09:45:00Z',
  },
  {
    id: '22',
    name: 'Raphaël Mercier',
    email: 'raphael.mercier@smartplanning.fr',
    role: 'viewer',
    status: 'actif',
    createdAt: '2024-05-05T14:30:00Z',
  },
  {
    id: '23',
    name: 'Clara Blanc',
    email: 'clara.blanc@smartplanning.fr',
    role: 'employee',
    status: 'inactif',
    createdAt: '2024-05-10T11:15:00Z',
  },
  {
    id: '24',
    name: 'Antoine Guerin',
    email: 'antoine.guerin@smartplanning.fr',
    role: 'manager',
    status: 'actif',
    createdAt: '2024-05-15T15:45:00Z',
  },
  {
    id: '25',
    name: 'Louise Boyer',
    email: 'louise.boyer@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-05-20T10:00:00Z',
  },
  {
    id: '26',
    name: 'Théo Chevalier',
    email: 'theo.chevalier@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-05-25T12:30:00Z',
  },
  {
    id: '27',
    name: 'Anaïs Lambert',
    email: 'anais.lambert@smartplanning.fr',
    role: 'viewer',
    status: 'actif',
    createdAt: '2024-06-01T09:00:00Z',
  },
  {
    id: '28',
    name: 'Benjamin Bonnet',
    email: 'benjamin.bonnet@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-06-05T14:15:00Z',
  },
  {
    id: '29',
    name: 'Juliette Faure',
    email: 'juliette.faure@smartplanning.fr',
    role: 'manager',
    status: 'actif',
    createdAt: '2024-06-10T11:30:00Z',
  },
  {
    id: '30',
    name: 'Paul Renaud',
    email: 'paul.renaud@smartplanning.fr',
    role: 'employee',
    status: 'inactif',
    createdAt: '2024-06-15T16:00:00Z',
  },
  {
    id: '31',
    name: 'Élise Colin',
    email: 'elise.colin@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-06-20T10:45:00Z',
  },
  {
    id: '32',
    name: 'Adam Leroy',
    email: 'adam.leroy@smartplanning.fr',
    role: 'viewer',
    status: 'actif',
    createdAt: '2024-06-25T13:15:00Z',
  },
  {
    id: '33',
    name: 'Mathilde Barbier',
    email: 'mathilde.barbier@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-07-01T09:30:00Z',
  },
  {
    id: '34',
    name: 'Tom Clement',
    email: 'tom.clement@smartplanning.fr',
    role: 'manager',
    status: 'actif',
    createdAt: '2024-07-05T14:00:00Z',
  },
  {
    id: '35',
    name: 'Margaux Gauthier',
    email: 'margaux.gauthier@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-07-10T11:00:00Z',
  },
  {
    id: '36',
    name: 'Victor Roussel',
    email: 'victor.roussel@smartplanning.fr',
    role: 'employee',
    status: 'inactif',
    createdAt: '2024-07-15T15:30:00Z',
  },
  {
    id: '37',
    name: 'Océane Masson',
    email: 'oceane.masson@smartplanning.fr',
    role: 'viewer',
    status: 'actif',
    createdAt: '2024-07-20T10:15:00Z',
  },
  {
    id: '38',
    name: 'Ethan Dumas',
    email: 'ethan.dumas@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-07-25T12:45:00Z',
  },
  {
    id: '39',
    name: 'Lola Dupuis',
    email: 'lola.dupuis@smartplanning.fr',
    role: 'manager',
    status: 'actif',
    createdAt: '2024-08-01T09:15:00Z',
  },
  {
    id: '40',
    name: 'Noah Carpentier',
    email: 'noah.carpentier@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-08-05T14:30:00Z',
  },
  {
    id: '41',
    name: 'Jade Leclerc',
    email: 'jade.leclerc@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-08-10T11:45:00Z',
  },
  {
    id: '42',
    name: 'Timéo Rousseau',
    email: 'timeo.rousseau@smartplanning.fr',
    role: 'viewer',
    status: 'actif',
    createdAt: '2024-08-15T16:00:00Z',
  },
  {
    id: '43',
    name: 'Rose Lopez',
    email: 'rose.lopez@smartplanning.fr',
    role: 'employee',
    status: 'inactif',
    createdAt: '2024-08-20T10:30:00Z',
  },
  {
    id: '44',
    name: 'Evan Perrin',
    email: 'evan.perrin@smartplanning.fr',
    role: 'manager',
    status: 'actif',
    createdAt: '2024-08-25T13:00:00Z',
  },
  {
    id: '45',
    name: 'Alice Meunier',
    email: 'alice.meunier@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-09-01T09:45:00Z',
  },
  {
    id: '46',
    name: 'Nolan Robin',
    email: 'nolan.robin@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-09-05T14:15:00Z',
  },
  {
    id: '47',
    name: 'Mia Renard',
    email: 'mia.renard@smartplanning.fr',
    role: 'viewer',
    status: 'actif',
    createdAt: '2024-09-10T11:30:00Z',
  },
  {
    id: '48',
    name: 'Sacha Marchand',
    email: 'sacha.marchand@smartplanning.fr',
    role: 'employee',
    status: 'actif',
    createdAt: '2024-09-15T15:45:00Z',
  },
  {
    id: '49',
    name: 'Charlie Rousset',
    email: 'charlie.rousset@smartplanning.fr',
    role: 'manager',
    status: 'actif',
    createdAt: '2024-09-20T10:00:00Z',
  },
  {
    id: '50',
    name: 'Anna Lefevre',
    email: 'anna.lefevre@smartplanning.fr',
    role: 'employee',
    status: 'inactif',
    createdAt: '2024-09-25T12:30:00Z',
  },
]
